
my_dna ="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
exon1 = my_dna[1:63]

exon2 = my_dna[91:10000]

print(exon1 + exon2)




my_dna ="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"

exon1 = my_dna[0:62]

exon2 = my_dna[90:10000]

print(exon1 + exon2)


my_dna ="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"

exon1 = my_dna[0:62]

exon2 = my_dna[90:10000]

coding_length = len(exon1 + exon2)

total_length = len(my_dna)

print(coding_length / total_length)


my_dna ="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"

exon1 = my_dna[0:62]

exon2 = my_dna[90:10000]

coding_length = len(exon1 + exon2)

total_length = len(my_dna)

print(100 * coding_length / total_length)

my_dna ="ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"

exon1 = my_dna[0:62]

intron = my_dna[62:90]

exon2 = my_dna[90:10000]

print(exon1 + intron.lower() + exon2)

